name: dclic_pay
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_credit_card: ^4.0.1
  lucide_icons: ^0.256.0
  water_drop_nav_bar: 2.2.2
  http: ^1.1.2  # Mise à jour
  fl_chart: ^0.63.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0  # Mise à jour
  flutter_native_splash: ^2.3.10  # Ajout pour écran de démarrage
  u_credit_card: ^1.4.0  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/1.png
     - assets/images/2.png
     - assets/images/3.png
     - assets/images/avatar_1.jpeg
     - assets/images/avatar_2.jpeg
     - assets/images/avatar_3.jpeg
     - assets/images/avatar_4.jpeg
     - assets/images/avatar_5.jpeg
     - assets/images/avatar_6.jpeg
